# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: '个人简历', folder: 'pages', file: 'resume.html'}
- {name: 'Python', folder: 'pages', file: 'python.html'}
- {name: 'Linux', folder: 'pages', file: 'linux.html'}
- {name: 'DB', folder: 'pages', file: 'db.html'}
- {name: 'CI', folder: 'pages', file: 'ci.html'}
- {name: '测试开发经验', folder: 'pages', file: 'test-dev.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'envelope', link: 'mailto:l.nguyen.paul@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
